#!/usr/bin/env bash

# const var to choose
BASE_DIRECTORY="$HOME/"
EDITOR="$EDITOR"
DEFAULT_TMUX_FIRST_WINDOW="1"
INSTALL_PATH="/usr/bin/tms"

# select directory and create new session
new_tmux_session()
{
    selected=$(find $BASE_DIRECTORY -mindepth 1 -maxdepth 11 -type d | fzf --algo=v2 --prompt="New session: ")
    
    if [ -z "$selected" ]; then
        return 1
    fi
    
    session_name=$(basename "$selected")
    session_path=$selected
    usr_shell=$(echo $SHELL)
    tmux new-session -Ad -s "$session_name" -c "$session_path" "$usr_shell"
    tmux send-keys -t "$session_name:$DEFAULT_TMUX_FIRST_WINDOW" "$EDITOR" Enter
    tmux new-window -t "$session_name:" -c "$session_path"
    tmux select-window -t "$session_name:$DEFAULT_TMUX_FIRST_WINDOW"
    if [ -n "$TMUX" ]; then
        tmux switch-client -t "$session_name"
    else
        tmux attach-session -t "$session_name"
    fi
}

# select current running session and attach to it
attach_tmux_session()
{
    if ! tmux list-sessions &>/dev/null; then
        echo "No tmux sessions running"
        return 1
    fi
    session_name=$(tmux list-sessions -F "#{session_name}" | fzf --prompt="Select session: ")
    
    if [ -z "$session_name" ]; then
        return 1
    fi
    
    if [ -n "$TMUX" ]; then
        tmux switch-client -t "$session_name"
    else
        tmux attach-session -t "$session_name"
    fi
}

# select current running session to kill
kill_tmux_session()
{
    if ! tmux list-sessions &>/dev/null; then
        return 1
    fi
    session_name=$(tmux list-sessions -F "#{session_name}" | fzf --prompt="Kill session: ")
    if [ -z "$session_name" ]; then
        return 1
    fi
    tmux kill-session -t "$session_name"
}

# ctrl + b + d interactive way
detach_tmux_session()
{
    if [ ! -n "$TMUX" ]; then
        return 1
    fi
    choice=$(echo -e "YES\nNO\n" | fzf --prompt="Detach from: \"$(tmux display-message -p '#S')\"")
    case $choice in 
        "YES") tmux detach-client ;;
        "NO") return 1;;
        *) return 1;;
    esac
    return 0
}

install()
{
    SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
    intallation_promp="Do you wnat to install tms (y/n) ? If you don't want to see this message try tms --no-install "

    if [ ! -f "$INSTALL_PATH" ]; then
        choice=$(echo -e "YES\nNO" | fzf --prompt="$intallation_promp")
        case "$choice" in 
          YES) sudo cp "$SCRIPT_PATH" "$INSTALL_PATH"
                sudo chmod +x $INSTALL_PATH
                echo "tms installed successfully from $SCRIPT_PATH to $INSTALL_PATH" 
              ;;
          NO) return 0;;
          * ) return 0;;
        esac
    fi
}

main()
{
    if [[ "$1" != "--no-install" ]]; then
        install
    fi

    while true; do
        choice=$(echo -e "NEW\nATTACH\nDETACH\nKILL\nEXIT" | fzf --prompt="tmux session manager: ")
        case $choice in
            "NEW") 
                new_tmux_session
                [ $? -eq 0 ] && break
                ;;
            "ATTACH") 
                attach_tmux_session
                [ $? -eq 0 ] && break
                ;;
            "DETACH")
                detach_tmux_session
                [ $? -eq 0 ] && break
                ;;
            "KILL") 
                kill_tmux_session
                ;;
            "EXIT" | "")
                break
                ;;
            *) 
                break
                ;;
        esac
    done
}

main "$@"
